### ISSUE TITLE
Player Klasse schreiben

### ISSUE THREAD

**Issue by TheNightglow** [JuliaHeise/Caterpillar#1]
Dinge die Wahrscheinlich benötigt werden:

Variablen:
Position, 
Score (ggf. Länge der Raupe falls durch andere Faktoren Länge != Score), 
Status (im Sinne aktiv. / deaktiviert (läuft nicht) aber sichtbar wenn Runde beendet/ nähste Runde noch nicht gestartet)

Constructor:
denke keine benötigte Parameter...
außer die Klasse kann nicht auf den Monogame Content File zugreifen, was ich fast befürchte...
(dann Model als Parameter...)

Funktionen:
- Laufrichtung muss änderbar sein (vllt Laufrichtungsparameter der je nach Key Abfrage in der Game1 Klasse durch eine Set Funktion geändert wird?)
- Pfadspeicherung hinsichtlich Raupenlänge sodass damit abgeglichen werden kann ob die Raupe
in sich selbst reinläuft

**Comment by JuliaHeise** [comment]
Der Player ist jetzt der Kopf der Raupe. Die Richtungsänderung und Bewegung erfolgt per Tastatureingabe. 
Der Körper muss noch so eingerichtet werden dass er die Bewegung des Kopfes mit Delay übernimmt. (Das kann auf die "Körperverlängerungen" übertragen werden)

Das Problem mit dem Content habe ich über eine Global Klasse gelöst. Dort werden GraphicDeviceManager und ContentManager initialsiert. So kann man von Jeder Klasse aus darauf zugreifen.
