### ISSUE TITLE
Pause bei klick Bug

### ISSUE THREAD

**Issue by JuliaHeise** [JuliaHeise/Caterpillar#11]
Bug: Das spiel pausiert immer wieder bei der Steuerung (Problem bei mauspad? - hat vorher eigentlich funktioniert)

zwischendurch ist es flüssig gelaufen.

**Comment by TheNightglow** [comment]
Hab dieses issue vollkommen übersehen^^

ist das Problem immernoch da? war vllt der unsichtbarkeitsbug den ich gefixt hab....
bzw das bei linksklick das Spiel pausiert hab ich so eingebaut, falls du das meinst^^

**Comment by JuliaHeise** [comment]
hab den bug immernoch. Vielleicht liegt es an dem mausclicker? wird könnten die pause auch einfach auf die rechte maustaste legen oder auf Q oder esc oder so?

**Comment by TheNightglow** [comment]
ja können wir machen
